services:
  app:
    image: dawn:latest
    build:
      context: .
    environment:
      - PORT=1312
      - APPLICATION_DATABASE_URL=file:/data/database.db
      - PRISMA_DATABASE_URL=file:/data/database.db
    ports:
      - "1312:1312"
    volumes:
      - ./data:/data
